name: protobuf
summary: Protocol Buffers compiler
description: >
  Protocol Buffers (a.k.a., protobuf) are Google's language-neutral,
  platform-neutral, extensible mechanism for serializing structured
  data. You can find protobuf's documentation at
  https://developers.google.com/protocol-buffers/
adopt-info: protobuf
type: app
base: core20
confinement: classic  # classic to allow protoc to call plugins
grade: stable
apps:
  protoc:
    command: bin/protoc
    environment:
      PATH: $SNAP/bin:$PATH
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib:$LD_LIBRARY_PATH
  protoc-gen-go:
    command: bin/protoc-gen-go
parts:
  protobuf:
    plugin: autotools
    build-packages:
      - unzip
      - curl
    source: https://github.com/protocolbuffers/protobuf.git
    source-type: git
    source-tag: v3.14.0
    override-pull: |
      snapcraftctl pull
      GIT_VER=$(git describe --dirty --always --tags | sed -r 's/v(.*)/\1/g')
      echo Pulled version $GIT_VER
      snapcraftctl set-version $GIT_VER
    autotools-configure-parameters:
      - "--prefix=/"
    stage:
      - bin
      - include
      - lib
  protoc-gen-go:
    plugin: go
    go-channel: latest/stable
    source: https://github.com/protocolbuffers/protobuf-go
    source-type: git
    source-tag: v1.25.0
    stage:
      - bin/protoc-gen-go
